notifications:
  slack: wtsi-cgpit:ptUMR1tkNyZJYd9TpGoss8WR
  email: false

env:
  - CC=gcc

addons:
  apt:
    packages:
      - build-essential # everything
      - autoconf # biobambam
      - libtool # biobambam
      - zlib1g-dev # many
      - nettle-dev # cgpBigWig
      - libncurses5-dev # samtools
      - unzip # kentools/pcap
      - libcurl4-openssl-dev # many
      - libdb-dev

install: true

language: perl

perl:
  - "5.22"

script:
  - set -e
  - export PATH=$HOME/install/bin:$HOME/install/biobambam2/bin:$PATH
  - git clone --depth 1 --single-branch --branch develop https://github.com/cancerit/cgpBigWig.git
  - cd cgpBigWig
  - ./setup.sh $HOME/install
  - cd ../
  - git clone --depth 1 --single-branch --branch develop https://github.com/cancerit/PCAP-core.git
  - cd PCAP-core
  - ./setup.sh $HOME/install
  - cd ../
  - git clone --depth 1 --single-branch --branch dev https://github.com/cancerit/cgpVcf.git
  - cd cgpVcf
  - ./setup.sh $HOME/install
  - cd ../
  - git clone --depth 1 --single-branch --branch dev https://github.com/cancerit/cgpCaVEManPostProcessing.git
  - cd cgpCaVEManPostProcessing
  - ./setup.sh $HOME/install
  - cd ../
  - ./setup.sh $HOME/install
  - cd ../
  - perl -I $HOME/install/lib/perl5 ~/install/bin/caveman.pl -v

dist: trusty
sudo: false
